import type { ChainLayer, FundingEvent, Policy, Region } from '../types';
import type { LLMResponse } from './llmClient';

export interface DemoPreset {
  label: string;
  response: LLMResponse;
}

// --- 预设 1: 政策 · 具身智能近期国家级动向 ---
const PRESET_POLICY_EMBODIED: Policy[] = [
  {
    id: 'demo-p-01',
    title: '工信部《人形机器人创新发展指导意见》',
    country: '中国',
    iso3: 'CHN',
    department: 'MIIT',
    departmentLabel: '工信部',
    level: 'ministerial',
    date: '2023-10',
    summary: '首次把人形机器人列为颠覆性产品,明确 2025 年初步建立创新体系、2027 年进入全球第一梯队,重点突破大脑/小脑/肢体关键部件。',
    fullTextUrl: 'https://www.miit.gov.cn/',
    relatedTechnologies: ['joint-control', 'servo-motor', 'computer-vision', 'reinforcement-learning'],
    relatedIndustries: ['humanoid-robot'],
    marketReactionDays: 7,
    innovationStage: 'applied-rd',
    keywords: ['具身智能', '人形机器人', '大脑小脑', '产业示范'],
    highlights: ['2025 年建成创新体系', '2027 年进入全球第一梯队', '重点攻关大脑/小脑/肢体'],
  },
  {
    id: 'demo-p-02',
    title: '科技部《具身智能重点研发专项》2024 年度指南',
    country: '中国',
    iso3: 'CHN',
    department: 'MoST',
    departmentLabel: '科技部',
    level: 'ministerial',
    date: '2024-07',
    summary: '聚焦多模态大模型、世界模型、仿真到真机迁移等基础科学问题,支持高校与国家实验室联合攻关。',
    fullTextUrl: 'https://www.most.gov.cn/',
    relatedTechnologies: ['llm-agent', 'reinforcement-learning', 'world-model', 'computer-vision'],
    relatedIndustries: ['humanoid-robot'],
    marketReactionDays: 20,
    innovationStage: 'basic-research',
    keywords: ['大模型', '世界模型', '仿真到真机', '基础研究'],
    highlights: ['多模态大模型底座', '世界模型前沿探索', '仿真-真机迁移'],
  },
  {
    id: 'demo-p-03',
    title: '工信部《推进新型工业化部署》',
    country: '中国',
    iso3: 'CHN',
    department: 'MIIT',
    departmentLabel: '工信部',
    level: 'ministerial',
    date: '2024-03',
    summary: '把智能制造、工业母机、工业软件与人形机器人并列为新型工业化主攻方向,强调产业链补短板、锻长板。',
    fullTextUrl: 'https://www.miit.gov.cn/',
    relatedTechnologies: ['servo-motor', 'joint-control', 'path-planning'],
    relatedIndustries: ['humanoid-robot', 'compute-grid'],
    marketReactionDays: 10,
    innovationStage: 'applied-rd',
    keywords: ['新型工业化', '智能制造', '工业母机', '补短板'],
    highlights: ['人形机器人列入主攻方向', '智能工厂示范', '供应链补短板'],
  },
  {
    id: 'demo-p-04',
    title: '北京市《促进机器人产业创新发展的若干措施》',
    country: '中国',
    iso3: 'CHN',
    department: 'NDRC',
    departmentLabel: '发改委',
    level: 'local',
    date: '2024-08',
    summary: '依托中关村与经开区,构建"大脑小脑肢体"协同创新生态,单项目最高 3000 万元研发补贴。',
    fullTextUrl: 'https://www.beijing.gov.cn/',
    relatedTechnologies: ['llm-agent', 'reinforcement-learning', 'computer-vision'],
    relatedIndustries: ['humanoid-robot'],
    marketReactionDays: 5,
    innovationStage: 'commercialization',
    keywords: ['北京', '机器人', '研发补贴', '中关村'],
    highlights: ['单项最高 3000 万补贴', '中关村示范区', '具身创新生态'],
  },
  {
    id: 'demo-p-05',
    title: '上海市《具身智能产业高质量发展行动方案》',
    country: '中国',
    iso3: 'CHN',
    department: 'NDRC',
    departmentLabel: '发改委',
    level: 'local',
    date: '2025-02',
    summary: '2027 年具身智能核心产业规模突破 500 亿元,打造"模型 + 本体 + 数据"三位一体产业体系。',
    fullTextUrl: 'https://www.shanghai.gov.cn/',
    relatedTechnologies: ['llm-agent', 'world-model', 'joint-control'],
    relatedIndustries: ['humanoid-robot', 'compute-grid'],
    marketReactionDays: 6,
    innovationStage: 'pilot',
    keywords: ['上海', '模型本体数据', '500 亿', '三位一体'],
    highlights: ['2027 年核心产业 500 亿', '张江具身训练场', '机器人谷集聚区'],
  },
  {
    id: 'demo-p-06',
    title: '中央经济工作会议:打造具身智能等未来产业新增长点',
    country: '中国',
    iso3: 'CHN',
    department: 'NDRC',
    departmentLabel: '发改委',
    level: 'national',
    date: '2024-12',
    summary: '首次在中央经济工作会议明确将具身智能列入"未来产业新增长点",产业资本进入长周期乐观预期。',
    fullTextUrl: 'https://www.gov.cn/',
    relatedTechnologies: ['llm-agent', 'world-model'],
    relatedIndustries: ['humanoid-robot'],
    marketReactionDays: 3,
    innovationStage: 'commercialization',
    keywords: ['中央经济工作会议', '未来产业', '新增长点'],
    highlights: ['写入中央经济工作会议', '未来产业新增长点', '长周期利好'],
  },
  {
    id: 'demo-p-07',
    title: '白宫《AI 行动计划》机器人专章',
    country: '美国',
    iso3: 'USA',
    department: 'International',
    departmentLabel: '国际',
    level: 'national',
    date: '2024-11',
    summary: '美国联邦将具身智能列入关键新兴技术清单,推动国防部采购与本土产业链国产化替代。',
    fullTextUrl: 'https://www.whitehouse.gov/',
    relatedTechnologies: ['reinforcement-learning', 'computer-vision'],
    relatedIndustries: ['humanoid-robot', 'compute-grid'],
    marketReactionDays: 2,
    innovationStage: 'applied-rd',
    keywords: ['美国', 'AI 行动计划', '关键新兴技术', '国防采购'],
    highlights: ['纳入关键新兴技术', '国防部采购试点', '本土产业链国产化'],
  },
  {
    id: 'demo-p-08',
    title: '欧盟《AI Act》及机器人安全补充条例',
    country: '欧盟',
    iso3: 'EUU',
    department: 'International',
    departmentLabel: '国际',
    level: 'supranational',
    date: '2024-08',
    summary: '欧盟针对高风险具身系统提出透明度义务 + CE 合规要求,出海欧洲机器人厂商需提前布局认证。',
    fullTextUrl: 'https://digital-strategy.ec.europa.eu/',
    relatedTechnologies: ['computer-vision'],
    relatedIndustries: ['humanoid-robot'],
    marketReactionDays: 30,
    innovationStage: 'commercialization',
    keywords: ['欧盟', 'AI Act', 'CE 合规', '出海'],
    highlights: ['高风险具身系统合规', 'CE 认证要求', '透明度义务'],
  },
];

// --- 预设 2: 产业 · 国内外人形机器人厂商对比 ---
const PRESET_INDUSTRY_HUMANOID: Region[] = [
  {
    id: 'demo-r-bj',
    name: '北京',
    englishName: 'Beijing',
    coordinates: { x: 68, y: 30 },
    endowment: '大模型策源地 · 中关村整机产业园 · 智元/银河通用总部',
    policies: [
      { id: 'demo-p-04', targetTrack: '整机与算法', focus: '单项最高 3000 万元研发补贴' },
      { id: 'demo-p-02', targetTrack: '基础研究', focus: '多模态大模型 + 世界模型' },
    ],
    scenarios: [
      { name: '智元机器人 · 远征 A1', description: '代表北京路线:多模态大模型驱动 + 端到端 VLA,面向工业与服务的通用本体。', technologies: ['llm-agent', 'reinforcement-learning', 'computer-vision'] },
      { name: '银河通用 · 具身大模型 Galbot', description: '与智源、北大联合,主打移动操作大模型底座。', technologies: ['llm-agent', 'world-model'] },
    ],
  },
  {
    id: 'demo-r-sh',
    name: '上海',
    englishName: 'Shanghai',
    coordinates: { x: 78, y: 52 },
    endowment: '张江机器人谷 · 浦东具身智能基地 · 金融与整车产业链协同',
    policies: [
      { id: 'demo-p-05', targetTrack: '整机 + 数据 + 模型', focus: '2027 年核心产业 500 亿' },
    ],
    scenarios: [
      { name: '傅利叶 GR-2', description: '医疗康复起家,转型通用人形,强调关节模组自研。', technologies: ['servo-motor', 'joint-control', 'force-sensor'] },
      { name: '开普勒 K2', description: '主打中等算力低成本方案,瞄准工业搬运与巡检。', technologies: ['computer-vision', 'path-planning'] },
    ],
  },
  {
    id: 'demo-r-gd',
    name: '广东',
    englishName: 'Guangdong',
    coordinates: { x: 70, y: 72 },
    endowment: '电子制造供应链完备 · 深圳创业资本 · 整机迭代速度全国最快',
    policies: [
      { id: 'demo-p-03', targetTrack: '智能制造', focus: '深圳/东莞整机带' },
    ],
    scenarios: [
      { name: '优必选 Walker S', description: '国内最早量产人形,进入比亚迪/蔚来工厂做装配测试。', technologies: ['servo-motor', 'joint-control', 'computer-vision'] },
      { name: '越疆 · Dobot Atom', description: '从机械臂出身,具备完整电机/控制器/算法自研链。', technologies: ['joint-control', 'force-sensor'] },
    ],
  },
  {
    id: 'demo-r-zj',
    name: '浙江',
    englishName: 'Zhejiang',
    coordinates: { x: 77, y: 55 },
    endowment: '宇树总部 · 之江实验室 · 电商/供应链场景密集',
    policies: [
      { id: 'demo-p-05', targetTrack: '整机 + 算力', focus: '杭州乌镇智算枢纽' },
    ],
    scenarios: [
      { name: '宇树 Unitree H1/G1', description: '四足起家,人形迭代极快,以低成本 + 运动控制著称。', technologies: ['servo-motor', 'joint-control', 'reinforcement-learning'] },
      { name: '云深处 Jueying', description: '工业巡检四足/轮足,强化学习控制。', technologies: ['reinforcement-learning', 'path-planning'] },
    ],
  },
  {
    id: 'demo-r-usa',
    name: '美国',
    englishName: 'USA',
    coordinates: { x: 22, y: 42 },
    endowment: 'Tesla/Figure/1X 三强 · 顶级算力 · 软件栈领先',
    policies: [
      { id: 'demo-p-07', targetTrack: 'AI 行动计划', focus: '国防采购 + 国产化' },
    ],
    scenarios: [
      { name: 'Tesla Optimus Gen-2', description: '纯视觉方案,复用自动驾驶 FSD 堆栈,目标工厂装配与家用。', technologies: ['computer-vision', 'reinforcement-learning', 'world-model'] },
      { name: 'Figure 02', description: '与 OpenAI 合作的 VLA 模型,BMW 工厂试点物流搬运。', technologies: ['llm-agent', 'reinforcement-learning'] },
      { name: '1X Neo', description: '面向家用服务机器人,软关节 + 布甲设计。', technologies: ['force-sensor', 'tactile-skin'] },
    ],
  },
  {
    id: 'demo-r-japan',
    name: '日本',
    englishName: 'Japan',
    coordinates: { x: 82, y: 46 },
    endowment: '精密减速器/伺服电机全球龙头 · 本体制造经验沉淀',
    policies: [
      { id: 'demo-p-08', targetTrack: '本体安全认证', focus: '机器人安全国际标准' },
    ],
    scenarios: [
      { name: 'Fanuc / Yaskawa 工业臂', description: '全球工业机器人四大家族之二,强在整机质量与可靠性。', technologies: ['servo-motor', 'joint-control'] },
      { name: 'Sanctuary AI Phoenix(美加合作)', description: '主打拟人手灵巧操作,17 个自由度灵巧手。', technologies: ['force-sensor', 'tactile-skin'] },
    ],
  },
];

// --- 预设 3: 市场 · 具身智能产业链热力 ---
const PRESET_MARKET_EMBODIED_CHAIN: ChainLayer[] = [
  {
    layer: '上游',
    items: [
      { name: 'GPU / AI 训练芯片', heat: 'hot', amount: '$220B', reason: 'H100/H200 + 国产卡需求爆炸' },
      { name: '谐波减速器', heat: 'hot', amount: '¥22B' },
      { name: '六维力传感器', heat: 'warm', amount: '¥6B', gap: true, reason: '高精度国产化率 < 30%,依赖 ATI / Schunk' },
      { name: '电子皮肤 / 多模态触觉', heat: 'cold', amount: '¥1.5B', gap: true, reason: '研发周期长,商业化慢,需国资长线资金' },
      { name: '低噪声关节电机', heat: 'warm', amount: '¥14B' },
    ],
  },
  {
    layer: '中游',
    items: [
      { name: '多模态 VLA 大模型', heat: 'hot', amount: '—', reason: '端到端范式成主战场' },
      { name: '仿真训练引擎', heat: 'warm', amount: '—', gap: true, reason: 'Isaac Sim/MuJoCo 国产替代缺失' },
      { name: '整机本体', heat: 'hot', amount: '¥35B' },
      { name: '灵巧手 / 末端执行器', heat: 'warm', amount: '¥4B', gap: true, reason: '自由度+感知联合优化难' },
    ],
  },
  {
    layer: '下游',
    items: [
      { name: '工厂装配 / 物流分拣', heat: 'hot', amount: '¥25B' },
      { name: '家庭陪伴服务', heat: 'cold', amount: '—', gap: true, reason: '安全/成本/可靠性尚不达 C 端' },
      { name: '商业接待 / 展陈', heat: 'warm', amount: '¥9B' },
      { name: '科研 / 教育训练场', heat: 'hot', amount: '¥7B' },
    ],
  },
];

const PRESET_MARKET_EMBODIED_FUNDING: FundingEvent[] = [
  { id: 'demo-f-01', company: 'Figure AI', round: 'Series C', amount: '$1.5B', date: '2025-02', track: '人形机器人整机', techId: 'embodied-ai' },
  { id: 'demo-f-02', company: '宇树科技', round: 'Series B+', amount: '¥1.2B', date: '2025-03', track: '四足 / 人形机器人', techId: 'embodied-ai' },
  { id: 'demo-f-03', company: '智元机器人', round: 'A2', amount: '¥600M', date: '2024-11', track: '人形机器人', techId: 'embodied-ai' },
  { id: 'demo-f-04', company: '银河通用', round: 'Pre-A', amount: '¥250M', date: '2025-01', track: '具身大模型', techId: 'embodied-ai' },
  { id: 'demo-f-05', company: '千寻智能', round: 'Angel+', amount: '¥80M', date: '2024-12', track: '端到端 VLA 模型', techId: 'embodied-ai' },
  { id: 'demo-f-06', company: 'Skild AI', round: 'Series A', amount: '$300M', date: '2024-09', track: '通用机器人基础模型', techId: 'embodied-ai' },
  { id: 'demo-f-07', company: '星海图', round: 'A+', amount: '¥300M', date: '2025-02', track: '通用机器人', techId: 'embodied-ai' },
  { id: 'demo-f-08', company: 'Physical Intelligence (π)', round: 'Series B', amount: '$400M', date: '2024-11', track: '具身基础模型', techId: 'embodied-ai' },
  { id: 'demo-f-09', company: '逐际动力', round: 'A', amount: '¥200M', date: '2024-10', track: '双足人形', techId: 'embodied-ai' },
  { id: 'demo-f-10', company: '傅利叶', round: 'D', amount: '¥800M', date: '2025-01', track: '人形整机', techId: 'embodied-ai' },
];

// --- 预设 4: 市场 · 量子计算产业链卡脖子 ---
const PRESET_MARKET_QUANTUM_CHAIN: ChainLayer[] = [
  {
    layer: '上游',
    items: [
      { name: '稀释制冷机', heat: 'warm', amount: '¥2B', gap: true, reason: 'BlueFors/Oxford 进口依赖,国产 10mK 指标仍有差距' },
      { name: '超导量子芯片', heat: 'hot', amount: '¥3B' },
      { name: '微波电子学(AWG/测控)', heat: 'warm', amount: '¥1.5B', gap: true, reason: '核心 ADC/DAC 依赖 ADI/TI' },
      { name: '激光与真空系统', heat: 'warm', amount: '¥1.2B' },
      { name: '离子阱芯片 / 光量子芯片', heat: 'warm', amount: '¥0.8B' },
    ],
  },
  {
    layer: '中游',
    items: [
      { name: '量子纠错编码', heat: 'hot', amount: '—', gap: true, reason: '逻辑量子比特阈值仍未突破' },
      { name: '量子编译 / 控制栈', heat: 'warm', amount: '—' },
      { name: '量子算法库', heat: 'warm', amount: '—' },
      { name: '整机集成', heat: 'hot', amount: '¥2B' },
    ],
  },
  {
    layer: '下游',
    items: [
      { name: '量子化学模拟', heat: 'warm', amount: '¥1B' },
      { name: '金融组合优化', heat: 'cold', amount: '—', gap: true, reason: '尚无实用级量子优势' },
      { name: '量子云服务', heat: 'warm', amount: '¥0.8B' },
      { name: '后量子密码', heat: 'hot', amount: '¥1.5B' },
    ],
  },
];

const PRESET_MARKET_QUANTUM_FUNDING: FundingEvent[] = [
  { id: 'demo-fq-01', company: 'PsiQuantum', round: 'Series E', amount: '$620M', date: '2025-02', track: '光量子计算', techId: 'quantum' },
  { id: 'demo-fq-02', company: 'Quantinuum', round: 'Growth', amount: '$300M', date: '2024-12', track: '离子阱量子', techId: 'quantum' },
  { id: 'demo-fq-03', company: '本源量子', round: 'C', amount: '¥600M', date: '2024-10', track: '超导量子计算', techId: 'quantum' },
  { id: 'demo-fq-04', company: 'IonQ', round: 'Secondary', amount: '$500M', date: '2024-11', track: '离子阱 + 算法', techId: 'quantum' },
  { id: 'demo-fq-05', company: '玻色量子', round: 'B', amount: '¥200M', date: '2025-01', track: '相干光量子', techId: 'quantum' },
  { id: 'demo-fq-06', company: '国盾量子', round: '增发', amount: '¥900M', date: '2024-12', track: '量子通信 + 计算', techId: 'quantum' },
  { id: 'demo-fq-07', company: 'Atom Computing', round: 'Series B', amount: '$60M', date: '2024-09', track: '中性原子', techId: 'quantum' },
  { id: 'demo-fq-08', company: 'Rigetti', round: 'Secondary', amount: '$100M', date: '2024-10', track: '超导量子', techId: 'quantum' },
];

// --- 预设 5: 政策 · 脑机接口近期动向 ---
const PRESET_POLICY_BCI: Policy[] = [
  {
    id: 'demo-p-bci-01',
    title: '科技部《脑科学与类脑研究重大项目》2023 年度指南',
    country: '中国',
    iso3: 'CHN',
    department: 'MoST',
    departmentLabel: '科技部',
    level: 'ministerial',
    date: '2023-05',
    summary: '聚焦侵入式脑机接口电极材料、神经解码算法、临床转化等前沿方向,单项最高 3000 万支持。',
    fullTextUrl: 'https://www.most.gov.cn/',
    relatedTechnologies: ['bci-implant', 'bci-dl-decoder', 'bci-closed-loop'],
    relatedIndustries: ['neural-prosthetics'],
    marketReactionDays: 21,
    innovationStage: 'basic-research',
    keywords: ['脑机接口', '类脑', '电极', '临床转化'],
    highlights: ['侵入式电极材料', '神经解码算法', '3000 万/项'],
  },
  {
    id: 'demo-p-bci-02',
    title: '工信部《脑机接口标准化技术委员会》成立公告',
    country: '中国',
    iso3: 'CHN',
    department: 'MIIT',
    departmentLabel: '工信部',
    level: 'ministerial',
    date: '2024-04',
    summary: '统筹脑机接口采集、解码、安全、伦理等标准体系建设,首批启动 12 项国家标准制定。',
    fullTextUrl: 'https://www.miit.gov.cn/',
    relatedTechnologies: ['bci-eeg-cap', 'bci-implant', 'bci-dl-decoder'],
    relatedIndustries: ['neural-prosthetics'],
    marketReactionDays: 12,
    innovationStage: 'applied-rd',
    keywords: ['标委会', '国标', '采集', '安全'],
    highlights: ['12 项国标启动', '伦理与安全标准', '采集/解码协议'],
  },
  {
    id: 'demo-p-bci-03',
    title: '十四五《脑科学与类脑研究重大项目》中期评估',
    country: '中国',
    iso3: 'CHN',
    department: 'NDRC',
    departmentLabel: '发改委',
    level: 'national',
    date: '2024-06',
    summary: '重点项目阶段性进入临床试验,脑机接口产业进入"从实验室到病床"关键窗口。',
    fullTextUrl: 'https://www.ndrc.gov.cn/',
    relatedTechnologies: ['bci-implant', 'bci-closed-loop'],
    relatedIndustries: ['neural-prosthetics'],
    marketReactionDays: 10,
    innovationStage: 'pilot',
    keywords: ['十四五', '中期评估', '临床试验'],
    highlights: ['进入临床试验阶段', '实验室到病床', '产业化窗口'],
  },
  {
    id: 'demo-p-bci-04',
    title: '美国 NIH 《BRAIN 2.0》计划延续拨款',
    country: '美国',
    iso3: 'USA',
    department: 'International',
    departmentLabel: '国际',
    level: 'national',
    date: '2024-09',
    summary: '联邦为 BRAIN 2.0 延续 10 年拨款,重点支持 Neuralink/Synchron 等民营 BCI 临床研究。',
    fullTextUrl: 'https://braininitiative.nih.gov/',
    relatedTechnologies: ['bci-implant', 'bci-dl-decoder'],
    relatedIndustries: ['neural-prosthetics'],
    marketReactionDays: 3,
    innovationStage: 'applied-rd',
    keywords: ['BRAIN 2.0', 'NIH', 'Neuralink'],
    highlights: ['10 年延续拨款', '民营 BCI 临床支持', '底层神经科学'],
  },
  {
    id: 'demo-p-bci-05',
    title: '上海市《脑机接口医疗器械先导区建设方案》',
    country: '中国',
    iso3: 'CHN',
    department: 'NDRC',
    departmentLabel: '发改委',
    level: 'local',
    date: '2024-11',
    summary: '张江建设国内首个 BCI 医疗器械先导区,明确绿色通道审批 + 临床数据共享机制。',
    fullTextUrl: 'https://www.shanghai.gov.cn/',
    relatedTechnologies: ['bci-implant', 'bci-closed-loop', 'bci-dl-decoder'],
    relatedIndustries: ['neural-prosthetics'],
    marketReactionDays: 5,
    innovationStage: 'commercialization',
    keywords: ['上海', 'BCI 先导区', '绿色通道'],
    highlights: ['绿色通道审批', '临床数据共享', '医疗器械集群'],
  },
  {
    id: 'demo-p-bci-06',
    title: '深圳市《脑科学与脑机接口医疗专项》',
    country: '中国',
    iso3: 'CHN',
    department: 'NDRC',
    departmentLabel: '发改委',
    level: 'local',
    date: '2025-01',
    summary: '深圳面向非侵入式 BCI 消费级应用发力,提出康复/睡眠/注意力场景示范项目。',
    fullTextUrl: 'https://www.sz.gov.cn/',
    relatedTechnologies: ['bci-eeg-cap', 'bci-fnirs'],
    relatedIndustries: ['neural-prosthetics'],
    marketReactionDays: 8,
    innovationStage: 'commercialization',
    keywords: ['深圳', '非侵入式', '消费级'],
    highlights: ['非侵入 BCI 消费场景', '康复/睡眠/注意力', '示范项目'],
  },
  {
    id: 'demo-p-bci-07',
    title: 'FDA《侵入式 BCI 临床试验指南》修订版',
    country: '美国',
    iso3: 'USA',
    department: 'International',
    departmentLabel: '国际',
    level: 'national',
    date: '2024-12',
    summary: 'FDA 更新侵入式 BCI 临床试验豁免与加急通道规则,Neuralink/Synchron/Precision 同步受益。',
    fullTextUrl: 'https://www.fda.gov/',
    relatedTechnologies: ['bci-implant'],
    relatedIndustries: ['neural-prosthetics'],
    marketReactionDays: 2,
    innovationStage: 'pilot',
    keywords: ['FDA', '侵入式 BCI', '加急通道'],
    highlights: ['豁免规则更新', '加急审批通道', '多家同步受益'],
  },
  {
    id: 'demo-p-bci-08',
    title: '欧盟《医疗器械法规 MDR》BCI 附则草案',
    country: '欧盟',
    iso3: 'EUU',
    department: 'International',
    departmentLabel: '国际',
    level: 'supranational',
    date: '2025-03',
    summary: '欧盟针对侵入式 BCI 设立专门附则,强调伦理审查 + 数据本地化要求。',
    fullTextUrl: 'https://health.ec.europa.eu/',
    relatedTechnologies: ['bci-implant', 'bci-closed-loop'],
    relatedIndustries: ['neural-prosthetics'],
    marketReactionDays: 25,
    innovationStage: 'commercialization',
    keywords: ['欧盟 MDR', 'BCI 附则', '伦理审查'],
    highlights: ['伦理审查要求', '数据本地化', '出海合规'],
  },
];

export const DEMO_PRESETS: DemoPreset[] = [
  {
    label: '近一年国家级具身智能政策梳理',
    response: { module: 'policy', payload: { policies: PRESET_POLICY_EMBODIED } },
  },
  {
    label: '国内外人形机器人整机厂商对比',
    response: { module: 'industry', payload: { regions: PRESET_INDUSTRY_HUMANOID } },
  },
  {
    label: '具身智能产业链资金热力图',
    response: { module: 'market', payload: { chain: PRESET_MARKET_EMBODIED_CHAIN, fundingEvents: PRESET_MARKET_EMBODIED_FUNDING } },
  },
  {
    label: '量子计算产业链卡脖子环节',
    response: { module: 'market', payload: { chain: PRESET_MARKET_QUANTUM_CHAIN, fundingEvents: PRESET_MARKET_QUANTUM_FUNDING } },
  },
  {
    label: '脑机接口临床政策动向',
    response: { module: 'policy', payload: { policies: PRESET_POLICY_BCI } },
  },
];
